// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Todo                            = require("./todo.js");
var ReactDOMRe                      = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact                     = require("reason-react/lib/js/src/reasonReact.js");
var $dot$slashregisterServiceWorker = require("./registerServiceWorker");

((require('./index.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Todo.make(/* array */[])), "root");

$dot$slashregisterServiceWorker.default();

/*  Not a pure module */
